# This is a generated file. Not intended for manual editing.
services:
  todo:
    build:
      context: "/Users/briuin/RiderProjects/todo/server"
      dockerfile: "todo/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/todo.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "todo:dev"
    ports: []
    volumes:
    - "/Users/briuin/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/briuin/RiderProjects/todo/server/todo:/app:rw"
    - "/Users/briuin/RiderProjects/todo/server:/src:rw"
    working_dir: "/app"
